services:
   _defaults:
      autoconfigure: true
      autowire: true
      public: false
      bind:
          $pageFinder: '@contao.routing.page_finder'
          $requestStack: '@request_stack'

   Cgoit\RobotsTxtBundle\:
      resource: ../src/*
